services:
  acbot:
    container_name: acbot
    image: "ghcr.io/gurase/acbot:main"
    environment:
      - DISCORD_TOKEN=YOUR DISCORD TOKEN HERE
      - CHANNEL_ID=YOUR CHANNEL ID HERE
      - SNOWAGER_ROLE_ID=YOUR SNOWAGER ROLE ID HERE
      - TURMAC_ROLE_ID=YOUR TURMAC ROLE ID HERE
      - DATE_FORMAT=%a, %b %d, %Y %I%p
